exports.rules = {
  'expect-matcher': 1,
  'expect-single-argument': 1,
  'named-spy': 0,
  'no-focused-tests': 1,
  'no-disabled-tests': 1,
  'no-describe-variables': 0,
  'no-spec-dupes': 1,
  'no-suite-dupes': 1,
  'missing-expect': 0,
  'no-suite-callback-args': 2,
  'no-assign-spyon': 0,
  'no-unsafe-spy': 1,
  'no-global-setup': 2,
  'no-promise-without-done-fail': 1,
  'no-expect-in-setup-teardown': 1,
  'new-line-between-declarations': 1,
  'new-line-before-expect': 1,
  'prefer-jasmine-matcher': 1,
  'prefer-to-have-been-called-with': 1
};
